name: building test for each PR
on: 
  push:
  pull_request:
  
jobs:
  build_test:
    runs-on: ubuntu-20.04

    steps:
     - name: Checkout
       uses: actions/checkout@v3

     - name: Initialize
       env:
        DEBIAN_FRONTEND: noninteractive
       run: |
        sudo apt-get update 
        sudo apt-get install --no-install-recommends -y \
          wget unzip git software-properties-common

     - name: Install Openfoam7
       env:
        DEBIAN_FRONTEND: noninteractive
       run: |
        wget -O - https://dl.openfoam.org/gpg.key | sudo apt-key add -
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
        sudo apt-get update
        sudo apt-get -y install openfoam7
   
     - name: Install Libtorch
       run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.11.0%2Bcpu.zip
        unzip libtorch-cxx11-abi-shared-with-deps-1.11.0+cpu.zip -d thirdParty
        rm libtorch-cxx11-abi-shared-with-deps-1.11.0+cpu.zip

     - name: clone
       run: |
        git clone https://github.com/deepmodeling/deepflame-dev.git
        cd deepflame-dev

     - name: cantera and build
       run: |
         wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
         sh Miniconda3-latest-Linux-x86_64.sh -b
         source ~/miniconda3/etc/profile.d/conda.sh
         conda create -n libcantera && conda activate libcantera
         conda install -c cantera libcantera-devel
         source /opt/openfoam7/etc/bashrc
         . install.sh
